//! Regenerates `src/group/g_table.rs`, the fixed-base comb table for the
//! P-224 generator.
//!
//! Run from the crate root:
//!   cargo run --release --example gen_g_table -p p224-safe-rust
//!
//! Entry (i, j), j in 1..=2^W-1, is the affine Montgomery encoding of
//! `j * 2^(W*i) * G`.  The emitted literals are re-checked entry by entry
//! against repeated `g1_add` from the generator by
//! `group::tests::base_table_entries_match_repeated_addition`.

use p224::group::*;
use p224::{fp_inv, fp_mul, Fp};
use std::fmt::Write as _;

const W: usize = 5;
const BITS: usize = 224;
const WINDOWS: usize = (BITS + W - 1) / W;
const TSIZE: usize = (1 << W) - 1;

fn affine(p: &G1) -> (Fp, Fp) {
    let mut zinv = Fp([0u64; 4]);
    fp_inv(&mut zinv, &p.z);
    let mut x = Fp([0u64; 4]);
    let mut y = Fp([0u64; 4]);
    fp_mul(&mut x, &p.x, &zinv);
    fp_mul(&mut y, &p.y, &zinv);
    (x, y)
}

fn main() {
    let mut s = String::new();
    s.push_str(&format!(
        "//! AUTO-GENERATED by `cargo run --release --example gen_g_table`.\n\
         //! Do not edit by hand; re-run the generator instead.\n\
         //!\n\
         //! Fixed-base comb table for the P-224 generator G.  Entry\n\
         //! `G_TABLE[i * {TSIZE} + (j - 1)]` is `[x, y]`, the affine\n\
         //! Montgomery-form coordinates of `j * 2^({W}*i) * G`, for\n\
         //! `i` in `0..{WINDOWS}` and `j` in `1..={TSIZE}`.\n\
         //!\n\
         //! {WINDOWS} windows x {TSIZE} entries x 2 coordinates x 32 bytes\n\
         //! = {} bytes of `.rodata`.\n\n",
        WINDOWS * TSIZE * 2 * 32
    ));
    s.push_str(&format!(
        "pub static G_TABLE: [[[u64; 4]; 2]; {}] = [\n",
        WINDOWS * TSIZE
    ));

    let mut base = g1_generator();
    for _i in 0..WINDOWS {
        let mut acc = base;
        for _j in 1..=TSIZE {
            let (x, y) = affine(&acc);
            write!(s, "    [[").unwrap();
            for w in x.0.iter() {
                write!(s, "0x{w:016x},").unwrap();
            }
            write!(s, "], [").unwrap();
            for w in y.0.iter() {
                write!(s, "0x{w:016x},").unwrap();
            }
            writeln!(s, "]],").unwrap();
            acc = g1_add(&acc, &base);
        }
        for _ in 0..W {
            base = g1_double(&base);
        }
    }
    s.push_str("];\n");

    std::fs::create_dir_all("src/group").unwrap();
    std::fs::write("src/group/g_table.rs", &s).unwrap();
    println!(
        "wrote src/group/g_table.rs: {} windows, {} entries/window, {} bytes of table, {} bytes of source",
        WINDOWS,
        TSIZE,
        WINDOWS * TSIZE * 2 * 32,
        s.len()
    );
}
