(** * Verified safe-Rust tower generator for BN254.
 *
 * This driver applies the Coq-verified [safe_rust_module] from
 * [ToSafeRustBody.v] to the BN254 function list. The translation is
 * proven correct by [SafeRustSimulation.safe_cmd_correct].
 *
 * The ONLY hand-written Rust is the leaf wrapper block below:
 * 9 extern "C" declarations + 9 safe fn wrappers. These are
 * zero-logic pointer casts (the actual implementations live in
 * stubs.rs or Jasmin assembly). ALL tower function bodies including
 * bn254_Fp2_opp and bn254_Fp2_inv are generated by btranslate.
 *
 * Usage:
 *   ./bn254_safe_tower_verified <output.rs>
 *)

open Bn254_rust_extracted

let ocaml_string (cs : char list) : string =
  let buf = Buffer.create (Stdlib.List.length cs) in
  Stdlib.List.iter (Buffer.add_char buf) cs;
  Buffer.contents buf

let () =
  let outfile = match Array.to_list Sys.argv with
    | [_; o] -> o
    | _ -> Printf.eprintf "Usage: %s <output.rs>\n" Sys.argv.(0); exit 2
  in
  let n = Zpos (XO (XO XH)) in  (* 4 limbs *)
  let leaf_names = Stdlib.List.map (fun (n, _) -> ocaml_string n) bn254_leaf_funcs in
  let tower = Stdlib.List.filter
    (fun (n, _) -> not (Stdlib.List.mem (ocaml_string n) leaf_names))
    bn254_all_funcs in
  let n_tower = Stdlib.List.length tower in
  Printf.eprintf "[verified_safe_tower] %d tower functions\n" n_tower;
  let decls = ocaml_string (type_decls n) in
  let bodies = ocaml_string (safe_rust_module n tower) in
  (* LEAF WRAPPERS — zero-logic shims between safe Rust and assembly.
     9 extern "C" declarations (including _bn254_inv from stubs.rs)
     + 9 safe fn wrappers (pointer casts only).
     ALL tower functions including Fp2_opp, Fp2_inv are generated
     by btranslate above. *)
  let leaf_wrappers = {|extern "C" {
    fn _bn254_add(out: *mut u64, x: *const u64, y: *const u64);
    fn _bn254_sub(out: *mut u64, x: *const u64, y: *const u64);
    fn _bn254_mul(out: *mut u64, x: *const u64, y: *const u64);
    fn _bn254_square(out: *mut u64, x: *const u64);
    fn _bn254_opp(out: *mut u64, x: *const u64);
    fn _bn254_felem_copy(out: *mut u64, x: *const u64);
    fn _bn254_from_word(out: *mut u64, w: u64);
    fn _bn254_select_znz(out: *mut u64, c: u64, x: *const u64, y: *const u64);
    fn _bn254_inv(out: *mut u64, x: *const u64);
}
#[inline] pub fn bn254_add(out: &mut Fp, x: &Fp, y: &Fp) { unsafe { _bn254_add(out.0.as_mut_ptr(), x.0.as_ptr(), y.0.as_ptr()) } }
#[inline] pub fn bn254_sub(out: &mut Fp, x: &Fp, y: &Fp) { unsafe { _bn254_sub(out.0.as_mut_ptr(), x.0.as_ptr(), y.0.as_ptr()) } }
#[inline] pub fn bn254_mul(out: &mut Fp, x: &Fp, y: &Fp) { unsafe { _bn254_mul(out.0.as_mut_ptr(), x.0.as_ptr(), y.0.as_ptr()) } }
#[inline] pub fn bn254_square(out: &mut Fp, x: &Fp) { unsafe { _bn254_square(out.0.as_mut_ptr(), x.0.as_ptr()) } }
#[inline] pub fn bn254_opp(out: &mut Fp, x: &Fp) { unsafe { _bn254_opp(out.0.as_mut_ptr(), x.0.as_ptr()) } }
#[inline] pub fn bn254_felem_copy(out: &mut Fp, x: &Fp) { unsafe { _bn254_felem_copy(out.0.as_mut_ptr(), x.0.as_ptr()) } }
#[inline] pub fn bn254_from_word(out: &mut Fp, w: u64) { unsafe { _bn254_from_word(out.0.as_mut_ptr(), w) } }
#[inline] pub fn bn254_select_znz(out: &mut Fp, c: u64, x: &Fp, y: &Fp) { unsafe { _bn254_select_znz(out.0.as_mut_ptr(), c, x.0.as_ptr(), y.0.as_ptr()) } }
#[inline] pub fn bn254_inv(out: &mut Fp, x: &Fp) { unsafe { _bn254_inv(out.0.as_mut_ptr(), x.0.as_ptr()) } }

|} in
  let text = decls ^ "\n" ^ leaf_wrappers ^ "\n" ^ bodies ^ "\n" in
  let oc = open_out outfile in
  output_string oc text;
  close_out oc;
  Printf.eprintf "[verified_safe_tower] wrote %d bytes to %s\n"
    (String.length text) outfile
