(include_subdirs qualified)

(coq.theory
 (name Bedrock)
 (mode vo)
 (flags -time)
 (modules
  (:standard
   \ ExtractSafeRust
     ExtractSafeTower
     ExtractSafeTowerBLS12
     TestSafeBody
     Field.bls12prime
     Field.pallasprime
     Field.vestaprime
     Field.bw6prime
     Field.quadratic_extension_bls12
     Field.testFp2
     Curve.BLS12Curve_G1
     Curve.BLS12Curve_G2
     Curve.PallasCurve_G1_bedrock
     Curve.VestaCurve_G1_bedrock
     Curve.BW6_761Curve_G1_bedrock
     Examples.felem_copy_32
     Examples.felem_copy_64
     Examples.felem_copy_p224_64
     Examples.p224_64_Fp2
     End2End.Ristretto.ScalarMult
     End2End.XEdDSA.Sign
     End2End.XEdDSA.Verify))
 (theories Stdlib Crypto Theory Implementations bedrock2 coqutil))
