#!/usr/bin/env python3
"""Generate the BN254 cross-check Rust example.

The output is `bn254-safe-rust/examples/multilin_test.rs`. It runs the
safe-Rust pairing for (k*G1, G2) and (G1, G2)^k for k ∈ {2,3,5,7,11} and
checks the bilinearity-style relation e(kP, Q) == e(P, Q)^k.

The kP coordinates are precomputed here (Python, py_ecc-compatible curve law)
and embedded as Montgomery limbs. To regenerate after a curve-data change,
re-run this script.

Usage:
    python3 tests/generate_bn254_multilin.py
    python3 tests/generate_bn254_multilin.py --optimal   # use pairing_optimal

The --optimal flag switches the generated test to call `pairing_optimal`
instead of `pairing`. This targets the bn254_pairing_dsd_optimal entry
point added in BN254_Pairing.v (Task 2, 2026-04-11), which uses the
Frobenius-corrected miller loop. Activate after re-running the extraction
pipeline AND uncommenting `pairing_optimal` in `bn254-safe-rust/src/lib.rs`.
"""

import sys

USE_OPTIMAL = "--optimal" in sys.argv
PAIRING_FN = "pairing_optimal" if USE_OPTIMAL else "pairing"
OUT_FILENAME = "multilin_test_optimal.rs" if USE_OPTIMAL else "multilin_test.rs"

p = 21888242871839275222246405745257275088696311157297823662689037894645226208583
R = 2**256 % p

KS = [2, 3, 5, 7, 11]


def to_mont(x):
    return (x * R) % p


def to_limbs(x):
    return [(x >> (64 * i)) & ((1 << 64) - 1) for i in range(4)]


def fmul(a, b):
    return (a * b) % p


def fadd(a, b):
    return (a + b) % p


def fsub(a, b):
    return (a - b) % p


def finv(a):
    return pow(a, p - 2, p)


def double_pt(P):
    x, y = P
    lam = fmul(fmul(3, fmul(x, x)), finv(fmul(2, y)))
    nx = fsub(fsub(fmul(lam, lam), x), x)
    ny = fsub(fmul(lam, fsub(x, nx)), y)
    return (nx, ny)


def add_pt(P, Q):
    if P is None:
        return Q
    if Q is None:
        return P
    x1, y1 = P
    x2, y2 = Q
    if x1 == x2 and y1 == y2:
        return double_pt(P)
    lam = fmul(fsub(y2, y1), finv(fsub(x2, x1)))
    nx = fsub(fsub(fmul(lam, lam), x1), x2)
    ny = fsub(fmul(lam, fsub(x1, nx)), y1)
    return (nx, ny)


def scalar_mul(k, P):
    R = None
    cur = P
    while k > 0:
        if k & 1:
            R = add_pt(R, cur)
        cur = double_pt(cur)
        k >>= 1
    return R


# BN254 G1 generator (1, 2)
G1 = (1, 2)


def fmt_fp(name, val):
    limbs = to_limbs(to_mont(val))
    return f"const {name}: Fp = Fp([{limbs[0]}, {limbs[1]}, {limbs[2]}, {limbs[3]}]);"


def main():
    out = []
    out.append("//! Generated by tests/generate_bn254_multilin.py — DO NOT EDIT BY HAND.")
    out.append("//!")
    out.append("//! Cross-check: e(k*G1, G2) == e(G1, G2)^k for k in {2,3,5,7,11}.")
    out.append("//! Both sides are computed inside the safe-Rust BN254 tower; the kP")
    out.append("//! coordinates are precomputed via Python's curve-law arithmetic.")
    out.append("")
    out.append("use bn254::*;")
    out.append("")
    out.append("// G1 generator (1, 2) in Montgomery form")
    out.append(fmt_fp("G1_X", G1[0]))
    out.append(fmt_fp("G1_Y", G1[1]))
    out.append("")

    for k in KS:
        kP = scalar_mul(k, G1)
        out.append(f"// {k}*G1 in Montgomery form")
        out.append(fmt_fp(f"K{k}_G1_X", kP[0]))
        out.append(fmt_fp(f"K{k}_G1_Y", kP[1]))
        out.append("")

    out.append("// G2 generator (the same one used by examples/pairing_test.rs)")
    out.append("fn g2() -> (Fp2, Fp2) {")
    out.append("    let q_x = Fp2 {")
    out.append("        c0: Fp([0x8e83b5d102bc2026, 0xdceb1935497b0172, 0xfbb8264797811adf, 0x19573841af96503b]),")
    out.append("        c1: Fp([0xafb4737da84c6140, 0x6043dd5a5802d8c4, 0x09e950fc52a02f86, 0x14fef0833aea7b6b]),")
    out.append("    };")
    out.append("    let q_y = Fp2 {")
    out.append("        c0: Fp([0x619dfa9d886be9f6, 0xfe7fd297f59e9b78, 0xff9e1a62231b7dfe, 0x28fd7eebae9e4206]),")
    out.append("        c1: Fp([0x64095b56c71856ee, 0xdc57f922327d3cbb, 0x55f935be33351076, 0x0da4a0e693fd6482]),")
    out.append("    };")
    out.append("    (q_x, q_y)")
    out.append("}")
    out.append("")
    out.append("/// Compute base^k in Fp12 by left-to-right square-and-multiply.")
    out.append("/// k must be a small positive integer.")
    out.append("fn fp12_pow_small(out: &mut Fp12, base: &Fp12, k: u64) {")
    out.append("    assert!(k >= 1);")
    out.append("    let mut acc = *base;")
    out.append("    let bits = 64 - k.leading_zeros();")
    out.append("    for i in (0..bits - 1).rev() {")
    out.append("        let prev = acc;")
    out.append("        bn254::fp12_square(&mut acc, &prev);")
    out.append("        if (k >> i) & 1 == 1 {")
    out.append("            let prev = acc;")
    out.append("            bn254::fp12_mul(&mut acc, &prev, base);")
    out.append("        }")
    out.append("    }")
    out.append("    *out = acc;")
    out.append("}")
    out.append("")
    out.append("fn fp12_eq(a: &Fp12, b: &Fp12) -> bool {")
    out.append("    a.c0.c0.c0 == b.c0.c0.c0 && a.c0.c0.c1 == b.c0.c0.c1 &&")
    out.append("    a.c0.c1.c0 == b.c0.c1.c0 && a.c0.c1.c1 == b.c0.c1.c1 &&")
    out.append("    a.c0.c2.c0 == b.c0.c2.c0 && a.c0.c2.c1 == b.c0.c2.c1 &&")
    out.append("    a.c1.c0.c0 == b.c1.c0.c0 && a.c1.c0.c1 == b.c1.c0.c1 &&")
    out.append("    a.c1.c1.c0 == b.c1.c1.c0 && a.c1.c1.c1 == b.c1.c1.c1 &&")
    out.append("    a.c1.c2.c0 == b.c1.c2.c0 && a.c1.c2.c1 == b.c1.c2.c1")
    out.append("}")
    out.append("")
    out.append("fn check(k: u64, kp_x: &Fp, kp_y: &Fp, q_x: &Fp2, q_y: &Fp2) -> bool {")
    out.append("    let mut e_pq = Fp12::zero();")
    out.append(f"    {PAIRING_FN}(&mut e_pq, &G1_X, &G1_Y, q_x, q_y);")
    out.append("    let mut e_kpq = Fp12::zero();")
    out.append(f"    {PAIRING_FN}(&mut e_kpq, kp_x, kp_y, q_x, q_y);")
    out.append("    let mut e_pq_k = Fp12::zero();")
    out.append("    fp12_pow_small(&mut e_pq_k, &e_pq, k);")
    out.append("    fp12_eq(&e_kpq, &e_pq_k)")
    out.append("}")
    out.append("")
    out.append("fn main() {")
    out.append("    let (q_x, q_y) = g2();")
    out.append("    let mut all_ok = true;")
    for k in KS:
        out.append(
            f"    let ok{k} = check({k}, &K{k}_G1_X, &K{k}_G1_Y, &q_x, &q_y);"
        )
        out.append(
            f'    println!("k={k}: {{}}", if ok{k} {{ "OK" }} else {{ "FAIL" }});'
        )
        out.append(f"    all_ok &= ok{k};")
    out.append("    if !all_ok {")
    out.append('        eprintln!("BN254 cross-check FAILED");')
    out.append("        std::process::exit(1);")
    out.append("    }")
    out.append('    println!("BN254 multilinearity cross-check PASS");')
    out.append("}")
    out.append("")
    return "\n".join(out)


if __name__ == "__main__":
    import sys
    import os

    text = main()
    target = os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        "..",
        "bn254-safe-rust",
        "examples",
        OUT_FILENAME,
    )
    target = os.path.normpath(target)
    with open(target, "w") as f:
        f.write(text)
    print(f"wrote {target} ({len(text)} bytes)", file=sys.stderr)
