#!/usr/bin/env python3
"""Generate the BLS12-381 cross-check Rust example.

Mirrors tests/generate_bn254_multilin.py — see that file for rationale.
Output: bls12-381-safe-rust/examples/multilin_test.rs
"""

p = 0x1A0111EA397FE69A4B1BA7B6434BACD764774B84F38512BF6730D2A0F6B0F6241EABFFFEB153FFFFB9FEFFFFFFFFAAAB
R = 2**384 % p

KS = [2, 3, 5, 7]


def to_mont(x):
    return (x * R) % p


def to_limbs(x):
    return [(x >> (64 * i)) & ((1 << 64) - 1) for i in range(6)]


def fmul(a, b):
    return (a * b) % p


def fadd(a, b):
    return (a + b) % p


def fsub(a, b):
    return (a - b) % p


def finv(a):
    return pow(a, p - 2, p)


def double_pt(P):
    x, y = P
    lam = fmul(fmul(3, fmul(x, x)), finv(fmul(2, y)))
    nx = fsub(fsub(fmul(lam, lam), x), x)
    ny = fsub(fmul(lam, fsub(x, nx)), y)
    return (nx, ny)


def add_pt(P, Q):
    if P is None:
        return Q
    if Q is None:
        return P
    x1, y1 = P
    x2, y2 = Q
    if x1 == x2 and y1 == y2:
        return double_pt(P)
    lam = fmul(fsub(y2, y1), finv(fsub(x2, x1)))
    nx = fsub(fsub(fmul(lam, lam), x1), x2)
    ny = fsub(fmul(lam, fsub(x1, nx)), y1)
    return (nx, ny)


def scalar_mul(k, P):
    R = None
    cur = P
    while k > 0:
        if k & 1:
            R = add_pt(R, cur)
        cur = double_pt(cur)
        k >>= 1
    return R


# BLS12-381 G1 generator
G1 = (
    0x17F1D3A73197D7942695638C4FA9AC0FC3688C4F9774B905A14E3A3F171BAC586C55E83FF97A1AEFFB3AF00ADB22C6BB,
    0x08B3F481E3AAA0F1A09E30ED741D8AE4FCF5E095D5D00AF600DB18CB2C04B3EDD03CC744A2888AE40CAA232946C5E7E1,
)


def fmt_fp(name, val):
    limbs = to_limbs(to_mont(val))
    return (
        f"const {name}: Fp = Fp(["
        + ", ".join(str(l) for l in limbs)
        + "]);"
    )


def main():
    out = []
    out.append("//! Generated by tests/generate_bls12_381_multilin.py — DO NOT EDIT BY HAND.")
    out.append("//!")
    out.append("//! Cross-check: e(k*G1, G2) == e(G1, G2)^k for k in {2,3,5,7}.")
    out.append("")
    out.append("use bls12_381::*;")
    out.append("")
    out.append("// G1 generator in Montgomery form")
    out.append(fmt_fp("G1_X", G1[0]))
    out.append(fmt_fp("G1_Y", G1[1]))
    out.append("")

    for k in KS:
        kP = scalar_mul(k, G1)
        out.append(f"// {k}*G1 in Montgomery form")
        out.append(fmt_fp(f"K{k}_G1_X", kP[0]))
        out.append(fmt_fp(f"K{k}_G1_Y", kP[1]))
        out.append("")

    out.append("// G2 generator (the same one used by examples/pairing_test.rs)")
    out.append("fn g2() -> (Fp2, Fp2) {")
    out.append("    let q_x = Fp2 {")
    out.append("        c0: Fp([17722385409647053328, 12967546844987299354, 11648722842835150208,")
    out.append("                10994581490347323113, 8027586497049998955, 396758299565931735]),")
    out.append("        c1: Fp([11937283898719073798, 12295044263989567683, 4301357764460312582,")
    out.append("                1953074377943790439, 14030662337566180679, 1266120665323335155]),")
    out.append("    };")
    out.append("    let q_y = Fp2 {")
    out.append("        c0: Fp([5508758831087832138, 6448303779119275098, 16710190169160573786,")
    out.append("                13542242618704742751, 563980702369916322, 37152010398653157]),")
    out.append("        c1: Fp([12520284671833321565, 1777275927576994268, 9704602344324656032,")
    out.append("                8739618045342622522, 16651875250601773805, 804950956836789234]),")
    out.append("    };")
    out.append("    (q_x, q_y)")
    out.append("}")
    out.append("")
    out.append("/// Compute base^k in Fp12 by left-to-right square-and-multiply.")
    out.append("fn fp12_pow_small(out: &mut Fp12, base: &Fp12, k: u64) {")
    out.append("    assert!(k >= 1);")
    out.append("    let mut acc = *base;")
    out.append("    let bits = 64 - k.leading_zeros();")
    out.append("    for i in (0..bits - 1).rev() {")
    out.append("        let prev = acc;")
    out.append("        bls12_381::fp12_square(&mut acc, &prev);")
    out.append("        if (k >> i) & 1 == 1 {")
    out.append("            let prev = acc;")
    out.append("            bls12_381::fp12_mul(&mut acc, &prev, base);")
    out.append("        }")
    out.append("    }")
    out.append("    *out = acc;")
    out.append("}")
    out.append("")
    out.append("fn fp12_eq(a: &Fp12, b: &Fp12) -> bool {")
    out.append("    a.c0.c0.c0 == b.c0.c0.c0 && a.c0.c0.c1 == b.c0.c0.c1 &&")
    out.append("    a.c0.c1.c0 == b.c0.c1.c0 && a.c0.c1.c1 == b.c0.c1.c1 &&")
    out.append("    a.c0.c2.c0 == b.c0.c2.c0 && a.c0.c2.c1 == b.c0.c2.c1 &&")
    out.append("    a.c1.c0.c0 == b.c1.c0.c0 && a.c1.c0.c1 == b.c1.c0.c1 &&")
    out.append("    a.c1.c1.c0 == b.c1.c1.c0 && a.c1.c1.c1 == b.c1.c1.c1 &&")
    out.append("    a.c1.c2.c0 == b.c1.c2.c0 && a.c1.c2.c1 == b.c1.c2.c1")
    out.append("}")
    out.append("")
    out.append("fn check(k: u64, kp_x: &Fp, kp_y: &Fp, q_x: &Fp2, q_y: &Fp2) -> bool {")
    out.append("    let mut e_pq = Fp12::zero();")
    out.append("    pairing(&mut e_pq, &G1_X, &G1_Y, q_x, q_y);")
    out.append("    let mut e_kpq = Fp12::zero();")
    out.append("    pairing(&mut e_kpq, kp_x, kp_y, q_x, q_y);")
    out.append("    let mut e_pq_k = Fp12::zero();")
    out.append("    fp12_pow_small(&mut e_pq_k, &e_pq, k);")
    out.append("    fp12_eq(&e_kpq, &e_pq_k)")
    out.append("}")
    out.append("")
    out.append("fn main() {")
    out.append("    let (q_x, q_y) = g2();")
    out.append("    let mut all_ok = true;")
    for k in KS:
        out.append(
            f"    let ok{k} = check({k}, &K{k}_G1_X, &K{k}_G1_Y, &q_x, &q_y);"
        )
        out.append(
            f'    println!("k={k}: {{}}", if ok{k} {{ "OK" }} else {{ "FAIL" }});'
        )
        out.append(f"    all_ok &= ok{k};")
    out.append("    if !all_ok {")
    out.append('        eprintln!("BLS12-381 cross-check FAILED");')
    out.append("        std::process::exit(1);")
    out.append("    }")
    out.append('    println!("BLS12-381 multilinearity cross-check PASS");')
    out.append("}")
    out.append("")
    return "\n".join(out)


if __name__ == "__main__":
    import sys
    import os

    text = main()
    target = os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        "..",
        "bls12-381-safe-rust",
        "examples",
        "multilin_test.rs",
    )
    target = os.path.normpath(target)
    with open(target, "w") as f:
        f.write(text)
    print(f"wrote {target} ({len(text)} bytes)", file=sys.stderr)
