//! BLS12-377 — safe Rust tower over verified bedrock2 leaves.
//!
//! Architecture mirrors bn256-safe-rust:
//!   tower functions (Fp2 → Fp6 → Fp12 → pairing): safe Rust, 0 unsafe
//!   leaf Fp ops: thin unsafe wrappers → pure-Rust Montgomery stubs OR
//!                fiat-crypto-emitted ops (PENDING — see below)
//!
//! 6 limbs (377-bit prime padded to 384 bits for WBW Montgomery).
//! Curve: BLS12 with seed u = 0x8508c00000000001 (positive, unlike
//! BLS12-381 where u is negative).
//!
//! Pipeline that produced this crate:
//!   src/Bedrock/Field/Synthesis/Examples/BLS12_377_Pairing.v
//!     → src/Bedrock/ExtractSafeTowerBLS12_377.v (run via rocq compile,
//!       emits bls12_377_rust_extracted.{ml,mli})
//!     → src/Bedrock/bls12_377_safe_tower_main.ml (OCaml driver)
//!     → generated/bls12_377_safe_tower.rs (this crate)

#![allow(non_snake_case, non_camel_case_types)]
#![allow(unused_assignments, unused_variables, unused_mut, unused_parens, dead_code)]

// Safe tower generated by ToSafeRustBody.v (Coq-verified translation:
// SafeRustSimulation.safe_cmd_correct).  51 functions across Fp2/Fp6/
// Fp12 + Miller loop + final exponentiation + pairing.
pub mod tower {
    include!(concat!(env!("CARGO_MANIFEST_DIR"), "/generated/bls12_377_safe_tower.rs"));
}

// PENDING: src/stubs.rs with Rust implementations of the 9 leaf Fp ops
// (`bls12_377_{add,sub,mul,square,opp,felem_copy,from_word,select_znz,inv}`)
// against the BLS12-377 prime, in 6-limb Montgomery form.  Recommended
// path: register BLS12-377 in fiat-crypto's Makefile.examples (same
// recipe the Pasta agent used for Pallas/Vesta), then re-emit fiat-rust
// to get `fiat-rust/src/bls12_377_64.rs`, then wrap those ops here just
// like p256-safe-rust does.  Without the stubs, this crate compiles as
// the tower-mod-only library; linking a binary against the leaf externs
// will fail until the stubs land.

pub use tower::{Fp, Fp2, Fp6, Fp12};

/// Constant-time modular inverse on raw saturated 6×u64 limbs, via the
/// Bernstein–Yang divstep port shared from `safegcd-rs/`.  Works
/// regardless of whether the Montgomery-form leaf ops are wired —
/// safegcd operates on the canonical-form limbs directly.  Verified
/// against `src/Arithmetic/safegcd/divsteps_bls12_377_half.v`.
pub fn invert_raw(out: &mut [u64; 6], x: &[u64; 6]) {
    // BLS12-377 reuses the bls12_381 safegcd module (same chunk size 59,
    // same 6×u64 layout); the BLS12-377-specific cert lives next to it.
    safegcd::safegcd_bls12_381::bls12_invert_divstep_sat(out, x);
}
