//! BLS12-377 field arithmetic — fiat-rust leaves + Bernstein-Yang inverse.
//!
//! Field operations (add, sub, mul, square, opp, to/from Montgomery,
//! to/from bytes) come from the auto-generated, machine-checked
//! `fiat-crypto/fiat-rust/src/bls12_377_64.rs`.  Constant-time modular
//! inversion comes from the Bernstein-Yang divstep port in
//! `safegcd-rs/src/safegcd_bls12_377.rs` (BLS12-377-specific prime
//! constant; convergence cert in
//! `src/Arithmetic/safegcd/divsteps_bls12_377_half.v`).
//!
//! 377-bit prime, 6×u64 saturated limb representation.
//! Curve seed u = 0x8508c00000000001 (positive, unlike BLS12-381's
//! negative u).

#![allow(non_snake_case, non_camel_case_types)]
#![allow(unused_assignments, unused_variables, unused_mut, unused_parens, dead_code)]

pub use fiat_crypto::bls12_377_64::fiat_bls12_377_montgomery_domain_field_element as Fp;
pub use fiat_crypto::bls12_377_64::fiat_bls12_377_non_montgomery_domain_field_element as FpRaw;

use fiat_crypto::bls12_377_64::*;

#[inline] pub fn fp_add(out: &mut Fp, x: &Fp, y: &Fp)     { fiat_bls12_377_add(out, x, y) }
#[inline] pub fn fp_sub(out: &mut Fp, x: &Fp, y: &Fp)     { fiat_bls12_377_sub(out, x, y) }
#[inline] pub fn fp_mul(out: &mut Fp, x: &Fp, y: &Fp)     { fiat_bls12_377_mul(out, x, y) }
#[inline] pub fn fp_square(out: &mut Fp, x: &Fp)          { fiat_bls12_377_square(out, x) }
#[inline] pub fn fp_opp(out: &mut Fp, x: &Fp)             { fiat_bls12_377_opp(out, x) }
#[inline] pub fn fp_to_bytes(out: &mut [u8; 377/8 + (377%8>0) as usize], x: &Fp) {
    fiat_bls12_377_to_bytes(out, &x.0)
}
#[inline] pub fn fp_from_bytes(out: &mut FpRaw, bs: &[u8; 377/8 + (377%8>0) as usize]) {
    fiat_bls12_377_from_bytes(&mut out.0, bs)
}
#[inline] pub fn fp_to_montgomery(out: &mut Fp, x: &FpRaw)    { fiat_bls12_377_to_montgomery(out, x) }
#[inline] pub fn fp_from_montgomery(out: &mut FpRaw, x: &Fp)  { fiat_bls12_377_from_montgomery(out, x) }

/// Constant-time modular inverse via the Bernstein–Yang divstep port.
/// Input/output are in Montgomery form.  Convert out → invert → convert in.
pub fn fp_inv(out: &mut Fp, x: &Fp) {
    let mut raw_in = FpRaw([0u64; 6]);
    fp_from_montgomery(&mut raw_in, x);
    let mut raw_inv = [0u64; 6];
    safegcd::safegcd_bls12_377::bls12_377_invert_divstep_sat(&mut raw_inv, &raw_in.0);
    fp_to_montgomery(out, &FpRaw(raw_inv));
}

/// Bernstein–Yang raw inverse on canonical 6×u64 limbs (NOT in
/// Montgomery form).  Kept for callers that want to operate outside
/// the Montgomery domain.
pub fn invert_raw(out: &mut [u64; 6], x: &[u64; 6]) {
    safegcd::safegcd_bls12_377::bls12_377_invert_divstep_sat(out, x);
}

// Safe tower generated by ToSafeRustBody.v (Coq-verified translation:
// SafeRustSimulation.safe_cmd_correct).  51 functions across Fp2/Fp6/
// Fp12 + Miller loop + final exponentiation + pairing.  The tower
// declares its own opaque `Fp` and links against `_bls377_*` externs;
// it is kept under a sub-module to coexist with the fiat-wrapped Fp
// above.  Re-exported tower towers Fp2/Fp6/Fp12 below.
pub mod tower {
    include!(concat!(env!("CARGO_MANIFEST_DIR"), "/generated/bls12_377_safe_tower.rs"));
}

pub use tower::{Fp2, Fp6, Fp12};

#[cfg(test)]
mod kat;
