(** * Extract the complete BLS12-381 pairing pipeline to C.
    Produces C modules for:
    1. Base field Fp functions (from bls12_prime synthesis)
    2. All pairing functions: Fp2, Fp6, Fp12, Miller loop,
       final exponentiation, and top-level pairing. *)

From Stdlib Require Import Strings.String.
From Stdlib Require Import ZArith.ZArith.
Require Import bedrock2.ToCString.
Require Import bedrock2.Syntax.

Require Import Bedrock.Field.Synthesis.Examples.bls12_prime.
Require Import Bedrock.Field.Synthesis.Examples.bls12_felem_copy.
Require Import Bedrock.Field.FieldExtensions.QuadraticFieldExtensions.
Require Import Bedrock.Field.Synthesis.Examples.BLS12_Pairing.

Import BinInt String List.ListNotations.
Local Open Scope string_scope.
Local Open Scope Z_scope.
Local Open Scope list_scope.

Local Notation function_t := (String.string * (list String.string * list String.string * Syntax.cmd.cmd))%type.

(** Base Fp functions *)
Definition fp_base_funcs : list function_t :=
  [ bls12_add; bls12_sub; bls12_mul; bls12_square;
    bls12_select_znz;
    ("bls12_felem_copy", bls12_felem_copy) ].

(** Combined: Fp base + pairing pipeline (Fp6/Fp12/PairingOps/Miller/FinalExp/Pairing).
    Note: Fp2 base functions (add, sub, mul, etc.) and some Fp functions
    (opp, inv, from_word) are generated by the synthesis framework and
    require typeclass instances; they are extracted separately via bls12_Fp2.v.
    The pairing functions call them but their bodies are not included here;
    they must be linked from the Fp2 synthesis extraction. *)
Definition all_funcs : list function_t :=
  fp_base_funcs ++ BLS12_Pairing.bls12_all_pairing_funcs.

Definition all_c :=
  Eval vm_compute in c_module all_funcs.

Redirect "bls12_pairing_all" Eval cbv in all_c.
