//! BN254 pairing — safe Rust tower over verified Jasmin leaves.
//!
//! Architecture:
//!   47 tower functions (Fp2→Fp6→Fp12→pairing): safe Rust, 0 unsafe
//!   8 leaf Fp ops: thin unsafe wrappers → Jasmin assembly (or stubs)
//!   Borrow checker enforces bedrock2 sep-logic non-aliasing.

#![allow(non_snake_case, non_camel_case_types)]
#![allow(unused_assignments, unused_variables, unused_mut, unused_parens, dead_code)]

// Safe tower generated by ToSafeRustBody.v (pure Rocq, no OCaml)
mod tower {
    include!(concat!(env!("CARGO_MANIFEST_DIR"), "/generated/bn254_safe_tower.rs"));
}

// Simple leaf ops always provided in Rust (opp, from_word, felem_copy, select_znz).
// When jasminc is available, add/sub/mul/square come from Jasmin assembly.
// When not, stubs provide all ops.
mod stubs;

pub use tower::{Fp, Fp2, Fp6, Fp12};

pub fn fp_add(out: &mut Fp, x: &Fp, y: &Fp) { tower::bn254_add(out, x, y) }
pub fn fp_sub(out: &mut Fp, x: &Fp, y: &Fp) { tower::bn254_sub(out, x, y) }
pub fn fp_mul(out: &mut Fp, x: &Fp, y: &Fp) { tower::bn254_mul(out, x, y) }
pub fn fp_square(out: &mut Fp, x: &Fp) { tower::bn254_square(out, x) }

pub fn pairing(out: &mut Fp12, p_x: &Fp, p_y: &Fp, q_x: &Fp2, q_y: &Fp2) {
    tower::bn254_pairing_dsd(out, p_x, p_y, q_x, q_y)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_fp_add_disjoint() {
        let a = Fp([1, 2, 3, 4]);
        let b = Fp([5, 6, 7, 8]);
        let mut c = Fp::zero();
        fp_add(&mut c, &a, &b);
        assert_eq!(c.0, [6, 8, 10, 12]);
    }

    #[test]
    fn test_pairing_runs() {
        let p_x = Fp([1, 0, 0, 0]);
        let p_y = Fp([2, 0, 0, 0]);
        let q_x = Fp2::zero();
        let q_y = Fp2::zero();
        let mut out = Fp12::zero();
        pairing(&mut out, &p_x, &p_y, &q_x, &q_y);
        // Smoke test: pairing completes without panic
        let _ = out;
    }
}
