//! BN254 pairing — safe Rust tower over verified Jasmin leaves.
//!
//! Architecture:
//!   47 tower functions (Fp2→Fp6→Fp12→pairing): safe Rust, 0 unsafe
//!   8 leaf Fp ops: thin unsafe wrappers → Jasmin assembly (or stubs)
//!   Borrow checker enforces bedrock2 sep-logic non-aliasing.

#![allow(non_snake_case, non_camel_case_types)]
#![allow(unused_assignments, unused_variables, unused_mut, unused_parens, dead_code)]

// Safe tower generated by ToSafeRustBody.v (pure Rocq, no OCaml)
pub mod tower {
    include!(concat!(env!("CARGO_MANIFEST_DIR"), "/generated/bn254_safe_tower.rs"));
}

// Simple leaf ops always provided in Rust (opp, from_word, felem_copy, select_znz).
// stubs.rs provides Rust implementations of the eight `_bn254_*` extern-C
// leaves.  When the `jasmin` feature is active, the heavy four
// (add/sub/mul/square) are supplied instead by libbn254_leaves.a +
// jasmin_aliases.s; the other four (felem_copy/opp/from_word/inv) are
// stub-only either way.  The cfg flags inside stubs.rs gate the heavy
// four out so the linker does not pick the Rust stubs over the Jasmin
// code (stubs would otherwise win the symbol race because they are
// first in link order).
mod stubs;

/// Byte-ABI shims (`*mut u8` / `*const u8` over the leaf byte slots)
/// for the Rocq-emitted bodies, over the crate's own leaves.
pub mod extracted_leaves;
/// Rocq-emitted RCB Algorithm 9 complete doubling (a = 0).
pub mod g1_double_a0_extracted;
#[cfg(test)]
mod g1_double_a0_test;


// Hand-coded projective Miller loop (UNVERIFIED, benchmark-only).
pub mod projective;

pub use tower::{Fp, Fp2, Fp6, Fp12};

pub fn fp_add(out: &mut Fp, x: &Fp, y: &Fp) { tower::bn254_add(out, x, y) }
pub fn fp_sub(out: &mut Fp, x: &Fp, y: &Fp) { tower::bn254_sub(out, x, y) }
pub fn fp_mul(out: &mut Fp, x: &Fp, y: &Fp) { tower::bn254_mul(out, x, y) }
pub fn fp_square(out: &mut Fp, x: &Fp) { tower::bn254_square(out, x) }
pub fn fp_opp(out: &mut Fp, x: &Fp) { tower::bn254_opp(out, x) }
pub fn fp_inv(out: &mut Fp, x: &Fp) { tower::bn254_inv(out, x) }
pub fn fp_from_word(out: &mut Fp, w: u64) { tower::bn254_from_word(out, w) }
pub fn fp_copy(out: &mut Fp, x: &Fp) { tower::bn254_felem_copy(out, x) }

pub fn fp2_add(out: &mut Fp2, x: &Fp2, y: &Fp2) { tower::bn254_Fp2_add(out, x, y) }
pub fn fp2_sub(out: &mut Fp2, x: &Fp2, y: &Fp2) { tower::bn254_Fp2_sub(out, x, y) }
pub fn fp2_mul(out: &mut Fp2, x: &Fp2, y: &Fp2) { tower::bn254_Fp2_mul(out, x, y) }
pub fn fp2_square(out: &mut Fp2, x: &Fp2) { tower::bn254_Fp2_square(out, x) }
pub fn fp2_inv(out: &mut Fp2, x: &Fp2) { tower::bn254_Fp2_inv(out, x) }
pub fn fp2_opp(out: &mut Fp2, x: &Fp2) { tower::bn254_Fp2_opp(out, x) }

pub fn fp12_square(out: &mut Fp12, x: &Fp12) { tower::bn254_Fp12_square(out, x) }
pub fn fp12_mul(out: &mut Fp12, x: &Fp12, y: &Fp12) { tower::bn254_Fp12_mul(out, x, y) }
pub fn fp12_inv(out: &mut Fp12, x: &Fp12) { tower::bn254_Fp12_inv(out, x) }

pub fn pairing(out: &mut Fp12, p_x: &Fp, p_y: &Fp, q_x: &Fp2, q_y: &Fp2) {
    tower::bn254_pairing_dsd(out, p_x, p_y, q_x, q_y)
}

pub fn miller_loop(out: &mut Fp12, p_x: &Fp, p_y: &Fp, q_x: &Fp2, q_y: &Fp2) {
    tower::bn254_miller_loop(out, p_x, p_y, q_x, q_y)
}

// === Optimal-ate variants (after Frobenius corrections fix) ===
//
// These wrap the new bn254_miller_loop_optimal / bn254_pairing_dsd_optimal
// functions added to fiat-crypto/src/Bedrock/Field/Synthesis/Examples/BN254_Pairing.v
// (Task 2, 2026-04-11). Activate after re-running the extraction pipeline:
//
//   cd fiat-crypto && dune build src/Bedrock/Field/Synthesis/Examples/BN254_Pairing.vo
//   # then re-run safe-rust extraction (extract_safe_tower OCaml main)
//
// Once generated/bn254_safe_tower.rs contains bn254_miller_loop_optimal and
// bn254_pairing_dsd_optimal, uncomment the block below.
//
pub fn miller_loop_optimal(out: &mut Fp12, p_x: &Fp, p_y: &Fp, q_x: &Fp2, q_y: &Fp2) {
    tower::bn254_miller_loop_optimal(out, p_x, p_y, q_x, q_y)
}

pub fn pairing_optimal(out: &mut Fp12, p_x: &Fp, p_y: &Fp, q_x: &Fp2, q_y: &Fp2) {
    tower::bn254_pairing_dsd_optimal(out, p_x, p_y, q_x, q_y)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_fp_add_disjoint() {
        let a = Fp([1, 2, 3, 4]);
        let b = Fp([5, 6, 7, 8]);
        let mut c = Fp::zero();
        fp_add(&mut c, &a, &b);
        assert_eq!(c.0, [6, 8, 10, 12]);
    }

    #[test]
    fn test_mont_mul_3_times_5_is_15() {
        unsafe extern "C" {
            fn _bn254_from_word(o: *mut u64, w: u64);
            fn _bn254_mul(o: *mut u64, x: *const u64, y: *const u64);
        }
        unsafe {
            let mut three = [0u64; 4];
            let mut five = [0u64; 4];
            let mut fifteen_expected = [0u64; 4];
            let mut fifteen_actual = [0u64; 4];
            _bn254_from_word(three.as_mut_ptr(), 3);
            _bn254_from_word(five.as_mut_ptr(), 5);
            _bn254_from_word(fifteen_expected.as_mut_ptr(), 15);
            _bn254_mul(fifteen_actual.as_mut_ptr(), three.as_ptr(), five.as_ptr());
            assert_eq!(
                fifteen_expected, fifteen_actual,
                "3*5 in Montgomery form should equal 15 in Montgomery form"
            );
        }
    }

    #[test]
    fn test_fp2_mul_one_one_is_one() {
        // (1, 0) * (1, 0) should be (1, 0) in Fp2 = Fp[u]/(u^2+1)
        let mut one = Fp::zero();
        unsafe {
            unsafe extern "C" {
                fn _bn254_from_word(o: *mut u64, w: u64);
            }
            _bn254_from_word(one.0.as_mut_ptr(), 1);
        }
        let one_fp2 = Fp2 { c0: one, c1: Fp::zero() };
        let mut out = Fp2::zero();
        tower::bn254_Fp2_mul(&mut out, &one_fp2, &one_fp2);
        assert_eq!(out.c0, one, "Fp2 (1, 0) * (1, 0) should give c0 = 1");
        assert_eq!(out.c1, Fp::zero(), "Fp2 (1, 0) * (1, 0) should give c1 = 0");
    }

    #[test]
    fn test_pairing_runs() {
        let p_x = Fp([1, 0, 0, 0]);
        let p_y = Fp([2, 0, 0, 0]);
        let q_x = Fp2::zero();
        let q_y = Fp2::zero();
        let mut out = Fp12::zero();
        pairing(&mut out, &p_x, &p_y, &q_x, &q_y);
        // Smoke test: pairing completes without panic
        let _ = out;
    }
}

#[cfg(test)]
mod arithmetic_tests {
    use super::*;

    #[test]
    fn test_fp_mul_3x5() {
        let a = Fp([0x7a17caa950ad28d7, 0x1f6ac17ae15521b9, 0x334bea4e696bd284, 0x2a1f6744ce179d8e]);
        let b = Fp([0xe4b1c5ae034e46ca, 0x9cdb2d3b64716da7, 0x47d8eb76d8dd067e, 0x15d0085520f5bbc3]);
        let mut c = Fp::zero();
        fp_mul(&mut c, &a, &b);
        assert_eq!(c.0, [0x71f4c4f3316dd717, 0x3f101d20c4e27e6a, 0x1f3a7cae0915bb1e, 0x110bca8c81af9320],
            "3 * 5 = 15 in Montgomery form");
    }

    #[test]
    fn test_fp_add_mont() {
        let a = Fp([0x7a17caa950ad28d7, 0x1f6ac17ae15521b9, 0x334bea4e696bd284, 0x2a1f6744ce179d8e]);
        let b = Fp([0xe4b1c5ae034e46ca, 0x9cdb2d3b64716da7, 0x47d8eb76d8dd067e, 0x15d0085520f5bbc3]);
        let mut c = Fp::zero();
        fp_add(&mut c, &a, &b);
        assert_eq!(c.0, [0x22a904407b7e725a, 0x24c48424dd54c4d4, 0xc2d4900ec0c780a5, 0x0f8b21270ddbb927],
            "3 + 5 = 8 in Montgomery form");
    }

    /// Test first iteration of Miller loop by checking T_x after doubling step
    #[test]
    fn test_first_doubling() {
        let q_x = Fp2 {
            c0: Fp([0x8e83b5d102bc2026, 0xdceb1935497b0172, 0xfbb8264797811adf, 0x19573841af96503b]),
            c1: Fp([0xafb4737da84c6140, 0x6043dd5a5802d8c4, 0x09e950fc52a02f86, 0x14fef0833aea7b6b]),
        };
        let q_y = Fp2 {
            c0: Fp([0x619dfa9d886be9f6, 0xfe7fd297f59e9b78, 0xff9e1a62231b7dfe, 0x28fd7eebae9e4206]),
            c1: Fp([0x64095b56c71856ee, 0xdc57f922327d3cbb, 0x55f935be33351076, 0x0da4a0e693fd6482]),
        };
        let p_x = Fp([0xd35d438dc58f0d9d, 0x0a78eb28f5c70b3d, 0x666ea36f7879462c, 0x0e0a77c19a07df2f]);
        let p_y = Fp([0xa6ba871b8b1e1b3a, 0x14f1d651eb8e167b, 0xccdd46def0f28c58, 0x1c14ef83340fbe5e]);

        let mut t_x = Fp2::zero();
        let mut t_y = Fp2::zero();
        tower::bn254_Fp2_felem_copy(&mut t_x, &q_x);
        tower::bn254_Fp2_felem_copy(&mut t_y, &q_y);

        // Compute lambda = 3*t_x^2 / (2*t_y)
        let mut tmp1 = Fp2::zero();
        let mut lambda = Fp2::zero();
        tower::bn254_Fp2_square(&mut tmp1, &t_x);
        tower::bn254_Fp2_add(&mut lambda, &tmp1, &tmp1);
        let lam_clone = lambda.clone();
        tower::bn254_Fp2_add(&mut lambda, &lam_clone, &tmp1);
        tower::bn254_Fp2_add(&mut tmp1, &t_y, &t_y);
        let tmp1_clone = tmp1.clone();
        tower::bn254_Fp2_inv(&mut tmp1, &tmp1_clone);
        let lam_clone = lambda.clone();
        tower::bn254_Fp2_mul(&mut lambda, &lam_clone, &tmp1);

        eprintln!("lambda.c0 = {:?}", lambda.c0.0);
        eprintln!("lambda.c1 = {:?}", lambda.c1.0);

        // Expected from Python:
        // lambda mont c0 = [3052585229727698089, 638593975792026956, 1173302413870526096, 422092457526404441]
        // lambda mont c1 = [13089288121611136563, 17461653877637527732, 18166539099616017567, 1154234554735654081]
        assert_eq!(lambda.c0.0, [3052585229727698089, 638593975792026956, 1173302413870526096, 422092457526404441],
            "lambda.c0 should match Python reference");
        assert_eq!(lambda.c1.0, [13089288121611136563, 17461653877637527732, 18166539099616017567, 1154234554735654081],
            "lambda.c1 should match Python reference");

        // Compute new T: x' = lam^2 - 2*t_x
        let mut tmp2 = Fp2::zero();
        tower::bn254_Fp2_square(&mut tmp1, &lambda);
        let tmp1_clone = tmp1.clone();
        tower::bn254_Fp2_sub(&mut tmp1, &tmp1_clone, &t_x);
        tower::bn254_Fp2_sub(&mut tmp2, &tmp1, &t_x);
        // tmp2 = new_x

        eprintln!("new_x.c0 = {:?}", tmp2.c0.0);
        // Expected from Python: [4815383978556499321, 15201348362950579125, 6323554572958211309, 3380048522697165890]
        assert_eq!(tmp2.c0.0, [4815383978556499321, 15201348362950579125, 6323554572958211309, 3380048522697165890],
            "new_x.c0 should match Python reference");
    }

    /// Miller loop output (before final exp) - dump for comparison with py_ecc
    #[test]
    fn test_miller_loop_output() {
        // G1 generator (1, 2) in Montgomery form
        let p_x = Fp([0xd35d438dc58f0d9d, 0x0a78eb28f5c70b3d, 0x666ea36f7879462c, 0x0e0a77c19a07df2f]);
        let p_y = Fp([0xa6ba871b8b1e1b3a, 0x14f1d651eb8e167b, 0xccdd46def0f28c58, 0x1c14ef83340fbe5e]);
        let q_x = Fp2 {
            c0: Fp([0x8e83b5d102bc2026, 0xdceb1935497b0172, 0xfbb8264797811adf, 0x19573841af96503b]),
            c1: Fp([0xafb4737da84c6140, 0x6043dd5a5802d8c4, 0x09e950fc52a02f86, 0x14fef0833aea7b6b]),
        };
        let q_y = Fp2 {
            c0: Fp([0x619dfa9d886be9f6, 0xfe7fd297f59e9b78, 0xff9e1a62231b7dfe, 0x28fd7eebae9e4206]),
            c1: Fp([0x64095b56c71856ee, 0xdc57f922327d3cbb, 0x55f935be33351076, 0x0da4a0e693fd6482]),
        };

        let mut f = Fp12::zero();
        miller_loop(&mut f, &p_x, &p_y, &q_x, &q_y);
        eprintln!("Miller loop c0.c0.c0 = {:?}", f.c0.c0.c0.0);
        eprintln!("Miller loop c0.c0.c1 = {:?}", f.c0.c0.c1.0);
        eprintln!("Miller loop c0.c1.c0 = {:?}", f.c0.c1.c0.0);
        eprintln!("Miller loop c0.c1.c1 = {:?}", f.c0.c1.c1.0);
        eprintln!("Miller loop c0.c2.c0 = {:?}", f.c0.c2.c0.0);
        eprintln!("Miller loop c0.c2.c1 = {:?}", f.c0.c2.c1.0);
        eprintln!("Miller loop c1.c0.c0 = {:?}", f.c1.c0.c0.0);
        eprintln!("Miller loop c1.c0.c1 = {:?}", f.c1.c0.c1.0);
        eprintln!("Miller loop c1.c1.c0 = {:?}", f.c1.c1.c0.0);
        eprintln!("Miller loop c1.c1.c1 = {:?}", f.c1.c1.c1.0);
        eprintln!("Miller loop c1.c2.c0 = {:?}", f.c1.c2.c0.0);
        eprintln!("Miller loop c1.c2.c1 = {:?}", f.c1.c2.c1.0);
    }

    /// Fp6_mul consistency: a * b * b^{-1} == a
    #[test]
    fn test_fp6_mul_inv() {
        // Use small values in Montgomery form
        let three = Fp([0x7a17caa950ad28d7, 0x1f6ac17ae15521b9, 0x334bea4e696bd284, 0x2a1f6744ce179d8e]);
        let four  = Fp([0x115482203dbf392d, 0x926242126eaa626a, 0xe16a48076063c052, 0x07c5909386eddc93]);
        let five  = Fp([0xe4b1c5ae034e46ca, 0x9cdb2d3b64716da7, 0x47d8eb76d8dd067e, 0x15d0085520f5bbc3]);
        let six   = Fp([0xb80f093bc8dd5467, 0xa75418645a3878e5, 0xae478ee651564caa, 0x23da8016bafd9af2]);
        let one   = Fp([0xd35d438dc58f0d9d, 0x0a78eb28f5c70b3d, 0x666ea36f7879462c, 0x0e0a77c19a07df2f]);

        let a = Fp6 {
            c0: Fp2 { c0: three, c1: four },
            c1: Fp2 { c0: five, c1: six },
            c2: Fp2 { c0: one, c1: three },
        };
        let b = Fp6 {
            c0: Fp2 { c0: five, c1: one },
            c1: Fp2 { c0: three, c1: four },
            c2: Fp2 { c0: six, c1: five },
        };

        let mut ab = Fp6::zero();
        tower::bn254_Fp6_mul(&mut ab, &a, &b);
        let mut b_inv = Fp6::zero();
        tower::bn254_Fp6_inv(&mut b_inv, &b);
        let mut result = Fp6::zero();
        tower::bn254_Fp6_mul(&mut result, &ab, &b_inv);

        assert_eq!(result.c0.c0, a.c0.c0, "Fp6 mul/inv c0.c0");
        assert_eq!(result.c0.c1, a.c0.c1, "Fp6 mul/inv c0.c1");
        assert_eq!(result.c1.c0, a.c1.c0, "Fp6 mul/inv c1.c0");
        assert_eq!(result.c1.c1, a.c1.c1, "Fp6 mul/inv c1.c1");
        assert_eq!(result.c2.c0, a.c2.c0, "Fp6 mul/inv c2.c0");
        assert_eq!(result.c2.c1, a.c2.c1, "Fp6 mul/inv c2.c1");
    }

    /// Fp12_mul consistency: a * b * b^{-1} == a
    #[test]
    fn test_fp12_mul_inv() {
        let three = Fp([0x7a17caa950ad28d7, 0x1f6ac17ae15521b9, 0x334bea4e696bd284, 0x2a1f6744ce179d8e]);
        let four  = Fp([0x115482203dbf392d, 0x926242126eaa626a, 0xe16a48076063c052, 0x07c5909386eddc93]);
        let five  = Fp([0xe4b1c5ae034e46ca, 0x9cdb2d3b64716da7, 0x47d8eb76d8dd067e, 0x15d0085520f5bbc3]);
        let six   = Fp([0xb80f093bc8dd5467, 0xa75418645a3878e5, 0xae478ee651564caa, 0x23da8016bafd9af2]);
        let one   = Fp([0xd35d438dc58f0d9d, 0x0a78eb28f5c70b3d, 0x666ea36f7879462c, 0x0e0a77c19a07df2f]);

        let a = Fp12 {
            c0: Fp6 {
                c0: Fp2 { c0: three, c1: four },
                c1: Fp2 { c0: five, c1: six },
                c2: Fp2 { c0: one, c1: three },
            },
            c1: Fp6 {
                c0: Fp2 { c0: four, c1: five },
                c1: Fp2 { c0: six, c1: one },
                c2: Fp2 { c0: three, c1: six },
            },
        };
        let b = Fp12 {
            c0: Fp6 {
                c0: Fp2 { c0: five, c1: one },
                c1: Fp2 { c0: three, c1: four },
                c2: Fp2 { c0: six, c1: five },
            },
            c1: Fp6 {
                c0: Fp2 { c0: one, c1: six },
                c1: Fp2 { c0: four, c1: three },
                c2: Fp2 { c0: five, c1: four },
            },
        };

        let mut ab = Fp12::zero();
        tower::bn254_Fp12_mul(&mut ab, &a, &b);
        let mut b_inv = Fp12::zero();
        tower::bn254_Fp12_inv(&mut b_inv, &b);
        let mut result = Fp12::zero();
        tower::bn254_Fp12_mul(&mut result, &ab, &b_inv);

        assert_eq!(result.c0.c0.c0, a.c0.c0.c0, "Fp12 mul/inv c0.c0.c0");
        assert_eq!(result.c0.c0.c1, a.c0.c0.c1, "Fp12 mul/inv c0.c0.c1");
        assert_eq!(result.c1.c0.c0, a.c1.c0.c0, "Fp12 mul/inv c1.c0.c0");
        // ... check all 12 components would be tedious, spot check first/last
        assert_eq!(result.c1.c2.c1, a.c1.c2.c1, "Fp12 mul/inv c1.c2.c1");
    }

    /// Fp2_mul_xi: (3+4i)*(9+i) = (27-4) + (3+36)i = 23 + 39i
    #[test]
    fn test_fp2_mul_xi() {
        let a = Fp2 {
            c0: Fp([0x7a17caa950ad28d7, 0x1f6ac17ae15521b9, 0x334bea4e696bd284, 0x2a1f6744ce179d8e]),  // 3
            c1: Fp([0x115482203dbf392d, 0x926242126eaa626a, 0xe16a48076063c052, 0x07c5909386eddc93]),  // 4
        };
        let mut result = Fp2::zero();
        tower::bn254_Fp2_mul_xi(&mut result, &a);

        // Expected: (3+4u)*(9+u) = (27-4) + (3+36)u = 23 + 39u  (since u^2 = -1)
        // Verify by computing via Fp2_mul with xi = (9, 1)
        let xi = Fp2 {
            c0: Fp([0xf60647ce410d7ff7, 0x2f3d6f4dd31bd011, 0x2943337e3940c6d1, 0x1d9598e8a7e39857]),  // 9
            c1: Fp([0xd35d438dc58f0d9d, 0x0a78eb28f5c70b3d, 0x666ea36f7879462c, 0x0e0a77c19a07df2f]),  // 1
        };
        let mut expected = Fp2::zero();
        tower::bn254_Fp2_mul(&mut expected, &a, &xi);

        assert_eq!(result.c0, expected.c0, "Fp2_mul_xi real part mismatch");
        assert_eq!(result.c1, expected.c1, "Fp2_mul_xi imag part mismatch");
    }

    /// Fp2_inv: (3+4i)^{-1} = (3-4i)/25 = 3/25 - 4i/25
    #[test]
    fn test_fp2_inv() {
        let a = Fp2 {
            c0: Fp([0x7a17caa950ad28d7, 0x1f6ac17ae15521b9, 0x334bea4e696bd284, 0x2a1f6744ce179d8e]),  // 3
            c1: Fp([0x115482203dbf392d, 0x926242126eaa626a, 0xe16a48076063c052, 0x07c5909386eddc93]),  // 4
        };
        let mut inv = Fp2::zero();
        tower::bn254_Fp2_inv(&mut inv, &a);
        // Check: a * inv == 1 (Fp2 identity)
        let mut product = Fp2::zero();
        tower::bn254_Fp2_mul(&mut product, &a, &inv);
        // Expected: c0 = Montgomery(1), c1 = Montgomery(0)
        let one = Fp([0xd35d438dc58f0d9d, 0x0a78eb28f5c70b3d, 0x666ea36f7879462c, 0x0e0a77c19a07df2f]);
        let zero = Fp([0, 0, 0, 0]);
        assert_eq!(product.c0, one, "Fp2_inv: real part of a*a^(-1) should be 1");
        assert_eq!(product.c1, zero, "Fp2_inv: imag part of a*a^(-1) should be 0");
    }

    /// Fp2_mul: (3+4i)*(5+6i) = (15-24) + (18+20)i = -9 + 38i  (beta = -1)
    #[test]
    fn test_fp2_mul() {
        let a = Fp2 {
            c0: Fp([0x7a17caa950ad28d7, 0x1f6ac17ae15521b9, 0x334bea4e696bd284, 0x2a1f6744ce179d8e]),  // 3
            c1: Fp([0x115482203dbf392d, 0x926242126eaa626a, 0xe16a48076063c052, 0x07c5909386eddc93]),  // 4
        };
        let b = Fp2 {
            c0: Fp([0xe4b1c5ae034e46ca, 0x9cdb2d3b64716da7, 0x47d8eb76d8dd067e, 0x15d0085520f5bbc3]),  // 5
            c1: Fp([0xb80f093bc8dd5467, 0xa75418645a3878e5, 0xae478ee651564caa, 0x23da8016bafd9af2]),  // 6
        };
        let mut c = Fp2::zero();
        tower::bn254_Fp2_mul(&mut c, &a, &b);

        let expected_c0 = Fp([0x461a4448976f7d50, 0x6843fb439555fa7b, 0x8f0d12384840918c, 0x12ceb58a394e07d2]);  // -9
        let expected_c1 = Fp([0xca72021005dd2341, 0x0b6353d4fea7f71b, 0x48f943b451719e84, 0x013e67cd30093f3e]);  // 38

        assert_eq!(c.c0.0, expected_c0.0, "Fp2_mul real part: expected -9 in Montgomery form");
        assert_eq!(c.c1.0, expected_c1.0, "Fp2_mul imag part: expected 38 in Montgomery form");
    }
}
