//! BN254 pairing — safe Rust tower over verified Jasmin leaves.
//!
//! Architecture:
//!   47 tower functions (Fp2→Fp6→Fp12→pairing): safe Rust, 0 unsafe
//!   8 leaf Fp ops: thin unsafe wrappers → Jasmin assembly (or stubs)
//!   Borrow checker enforces bedrock2 sep-logic non-aliasing.

#![allow(non_snake_case, non_camel_case_types)]
#![allow(unused_assignments, unused_variables, unused_mut, unused_parens, dead_code)]

// Safe tower generated by ToSafeRustBody.v (pure Rocq, no OCaml)
mod tower {
    include!(concat!(env!("CARGO_MANIFEST_DIR"), "/generated/bn254_safe_tower.rs"));
}

// Simple leaf ops always provided in Rust (opp, from_word, felem_copy, select_znz).
// When jasminc is available, add/sub/mul/square come from Jasmin assembly.
// When not, stubs provide all ops.
mod stubs;

pub use tower::{Fp, Fp2, Fp6, Fp12};

pub fn fp_add(out: &mut Fp, x: &Fp, y: &Fp) { tower::bn254_add(out, x, y) }
pub fn fp_sub(out: &mut Fp, x: &Fp, y: &Fp) { tower::bn254_sub(out, x, y) }
pub fn fp_mul(out: &mut Fp, x: &Fp, y: &Fp) { tower::bn254_mul(out, x, y) }
pub fn fp_square(out: &mut Fp, x: &Fp) { tower::bn254_square(out, x) }

pub fn pairing(out: &mut Fp12, p_x: &Fp, p_y: &Fp, q_x: &Fp2, q_y: &Fp2) {
    tower::bn254_pairing_dsd(out, p_x, p_y, q_x, q_y)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_fp_add_disjoint() {
        let a = Fp([1, 2, 3, 4]);
        let b = Fp([5, 6, 7, 8]);
        let mut c = Fp::zero();
        fp_add(&mut c, &a, &b);
        assert_eq!(c.0, [6, 8, 10, 12]);
    }

    #[test]
    fn test_pairing_runs() {
        let p_x = Fp([1, 0, 0, 0]);
        let p_y = Fp([2, 0, 0, 0]);
        let q_x = Fp2::zero();
        let q_y = Fp2::zero();
        let mut out = Fp12::zero();
        pairing(&mut out, &p_x, &p_y, &q_x, &q_y);
        // Smoke test: pairing completes without panic
        let _ = out;
    }
}

#[cfg(test)]
mod arithmetic_tests {
    use super::*;

    #[test]
    fn test_fp_mul_3x5() {
        let a = Fp([0x7a17caa950ad28d7, 0x1f6ac17ae15521b9, 0x334bea4e696bd284, 0x2a1f6744ce179d8e]);
        let b = Fp([0xe4b1c5ae034e46ca, 0x9cdb2d3b64716da7, 0x47d8eb76d8dd067e, 0x15d0085520f5bbc3]);
        let mut c = Fp::zero();
        fp_mul(&mut c, &a, &b);
        assert_eq!(c.0, [0x71f4c4f3316dd717, 0x3f101d20c4e27e6a, 0x1f3a7cae0915bb1e, 0x110bca8c81af9320],
            "3 * 5 = 15 in Montgomery form");
    }

    #[test]
    fn test_fp_add_mont() {
        let a = Fp([0x7a17caa950ad28d7, 0x1f6ac17ae15521b9, 0x334bea4e696bd284, 0x2a1f6744ce179d8e]);
        let b = Fp([0xe4b1c5ae034e46ca, 0x9cdb2d3b64716da7, 0x47d8eb76d8dd067e, 0x15d0085520f5bbc3]);
        let mut c = Fp::zero();
        fp_add(&mut c, &a, &b);
        assert_eq!(c.0, [0x22a904407b7e725a, 0x24c48424dd54c4d4, 0xc2d4900ec0c780a5, 0x0f8b21270ddbb927],
            "3 + 5 = 8 in Montgomery form");
    }
}
