//! Generated by tests/generate_bls12_381_multilin.py — DO NOT EDIT BY HAND.
//!
//! Cross-check: e(k*G1, G2) == e(G1, G2)^k for k in {2,3,5,7}.

use bls12_381::*;

// G1 generator in Montgomery form
const G1_X: Fp = Fp([6679831729115696150, 8653662730902241269, 1535610680227111361, 17342916647841752903, 17135755455211762752, 1297449291367578485]);
const G1_Y: Fp = Fp([13451288730302620273, 10097742279870053774, 15949884091978425806, 5885175747529691540, 1016841820992199104, 845620083434234474]);

// 2*G1 in Montgomery form
const K2_G1_X: Fp = Fp([6046496802367715900, 4512703842675942905, 5557647857818872160, 11911007586355426777, 2789226406901363231, 2402832991291269]);
const K2_G1_Y: Fp = Fp([8075247918781118784, 15723127573743364860, 13289805640942397317, 12593984073093990549, 2724610382811436832, 447576566110657301]);

// 3*G1 in Montgomery form
const K3_G1_X: Fp = Fp([14879952865637471106, 9101337358232323942, 14926506547533711328, 8345368023003003344, 7812449332930276794, 1206422667768826016]);
const K3_G1_Y: Fp = Fp([17400291712052253032, 15461228438443253073, 12497778704206688841, 16222987475149873513, 3298595310239752609, 1601199373778246201]);

// 5*G1 in Montgomery form
const K5_G1_X: Fp = Fp([7798803632276376933, 12696153824254828763, 9940482060148791282, 401870635790620626, 18018007387223068017, 860109884495846372]);
const K5_G1_Y: Fp = Fp([12665313621092566588, 4179163114239227577, 17976296434455888130, 9488934040161877222, 8720842450634292155, 1484499639674738680]);

// 7*G1 in Montgomery form
const K7_G1_X: Fp = Fp([13794385998538644597, 108816626937764141, 12130603454454490125, 6127379912259600201, 17481961476035825978, 950355161936836191]);
const K7_G1_Y: Fp = Fp([10722765800778186391, 17107915684035394744, 11626309118465119103, 5217919199071354366, 6102759180633827794, 660535627654889709]);

// G2 generator (the same one used by examples/pairing_test.rs)
fn g2() -> (Fp2, Fp2) {
    let q_x = Fp2 {
        c0: Fp([17722385409647053328, 12967546844987299354, 11648722842835150208,
                10994581490347323113, 8027586497049998955, 396758299565931735]),
        c1: Fp([11937283898719073798, 12295044263989567683, 4301357764460312582,
                1953074377943790439, 14030662337566180679, 1266120665323335155]),
    };
    let q_y = Fp2 {
        c0: Fp([5508758831087832138, 6448303779119275098, 16710190169160573786,
                13542242618704742751, 563980702369916322, 37152010398653157]),
        c1: Fp([12520284671833321565, 1777275927576994268, 9704602344324656032,
                8739618045342622522, 16651875250601773805, 804950956836789234]),
    };
    (q_x, q_y)
}

/// Compute base^k in Fp12 by left-to-right square-and-multiply.
fn fp12_pow_small(out: &mut Fp12, base: &Fp12, k: u64) {
    assert!(k >= 1);
    let mut acc = *base;
    let bits = 64 - k.leading_zeros();
    for i in (0..bits - 1).rev() {
        let prev = acc;
        bls12_381::fp12_square(&mut acc, &prev);
        if (k >> i) & 1 == 1 {
            let prev = acc;
            bls12_381::fp12_mul(&mut acc, &prev, base);
        }
    }
    *out = acc;
}

fn fp12_eq(a: &Fp12, b: &Fp12) -> bool {
    a.c0.c0.c0 == b.c0.c0.c0 && a.c0.c0.c1 == b.c0.c0.c1 &&
    a.c0.c1.c0 == b.c0.c1.c0 && a.c0.c1.c1 == b.c0.c1.c1 &&
    a.c0.c2.c0 == b.c0.c2.c0 && a.c0.c2.c1 == b.c0.c2.c1 &&
    a.c1.c0.c0 == b.c1.c0.c0 && a.c1.c0.c1 == b.c1.c0.c1 &&
    a.c1.c1.c0 == b.c1.c1.c0 && a.c1.c1.c1 == b.c1.c1.c1 &&
    a.c1.c2.c0 == b.c1.c2.c0 && a.c1.c2.c1 == b.c1.c2.c1
}

fn check(k: u64, kp_x: &Fp, kp_y: &Fp, q_x: &Fp2, q_y: &Fp2) -> bool {
    let mut e_pq = Fp12::zero();
    pairing(&mut e_pq, &G1_X, &G1_Y, q_x, q_y);
    let mut e_kpq = Fp12::zero();
    pairing(&mut e_kpq, kp_x, kp_y, q_x, q_y);
    let mut e_pq_k = Fp12::zero();
    fp12_pow_small(&mut e_pq_k, &e_pq, k);
    fp12_eq(&e_kpq, &e_pq_k)
}

fn main() {
    let (q_x, q_y) = g2();
    let mut all_ok = true;
    let ok2 = check(2, &K2_G1_X, &K2_G1_Y, &q_x, &q_y);
    println!("k=2: {}", if ok2 { "OK" } else { "FAIL" });
    all_ok &= ok2;
    let ok3 = check(3, &K3_G1_X, &K3_G1_Y, &q_x, &q_y);
    println!("k=3: {}", if ok3 { "OK" } else { "FAIL" });
    all_ok &= ok3;
    let ok5 = check(5, &K5_G1_X, &K5_G1_Y, &q_x, &q_y);
    println!("k=5: {}", if ok5 { "OK" } else { "FAIL" });
    all_ok &= ok5;
    let ok7 = check(7, &K7_G1_X, &K7_G1_Y, &q_x, &q_y);
    println!("k=7: {}", if ok7 { "OK" } else { "FAIL" });
    all_ok &= ok7;
    if !all_ok {
        eprintln!("BLS12-381 cross-check FAILED");
        std::process::exit(1);
    }
    println!("BLS12-381 multilinearity cross-check PASS");
}
