#!/bin/bash
# Time AUCurves build and extract per-file compile times.
# Usage: ./scripts/time_build.sh [dune-target]
# Default target: @src/all
#
# Output: scripts/build_timings.txt (sorted by wall time, descending)

set -euo pipefail
cd "$(dirname "$0")/.."

TARGET="${1:-@src/all}"
TRACE=/tmp/aucurves_trace_$$.json
TIMINGS=scripts/build_timings.txt

eval $(opam env --switch=rocq-native --set-switch)
ulimit -s unlimited

echo "Building $TARGET with timing..."
rm -f "$TRACE"

# Clean stale source artifacts
find fiat-crypto/src -maxdepth 10 \( -name "*.glob" -o -name "*.vo" \) \
  -not -path "*/_build/*" -delete 2>/dev/null || true

time dune build --trace-file "$TRACE" -j 2 "$TARGET" 2>&1 || true

# Parse dune trace (s-expression format) to extract per-file times
python3 -c "
import re, sys

with open('$TRACE') as f:
    data = f.read()

# Match process finish events with .v files
# Format: (process finish (timestamp dur) (process_args ...) (pid ...) ... (prog ...rocqworker) ... (exit 0) (rusage ((user_cpu_time N)...)))
# We look for rocqworker processes and their user_cpu_time
pattern = r'\(7:process6:finish\(19:\d+(\d+)\).*?\(4:prog\d+:([^)]+)\).*?\(3:dir\d+:([^)]*)\)\(4:exit(\d+)\)\(6:rusage\(\(13:user_cpu_time(\d+)\)'
matches = re.findall(pattern, data)

entries = []
for dur_ns, prog, _dir, exit_code, cpu_ns in matches:
    if 'rocqworker' in prog:
        wall_sec = int(dur_ns) / 1_000_000_000
        cpu_sec = int(cpu_ns) / 1_000_000
        entries.append((wall_sec, cpu_sec, exit_code))

# Alternative: just find all .vo build durations
# Look for build targets
vo_pattern = r'\(5:build\d+:target.*?(\d+:[\w/._]+\.vo).*?\)'
# This is complex in s-expressions. Fall back to process-based timing.

if not entries:
    print('No rocqworker timing found in trace. Using ps-based monitoring instead.', file=sys.stderr)
    sys.exit(0)

entries.sort(reverse=True)
for wall, cpu, ec in entries[:50]:
    if wall > 1.0:
        print(f'{wall:8.1f}s wall  {cpu:8.1f}s cpu  exit={ec}')
" 2>/dev/null > "$TIMINGS" || true

# If python parse failed, fall back to simple approach
if [ ! -s "$TIMINGS" ]; then
    echo "# AUCurves build timings ($(date +%Y-%m-%d))" > "$TIMINGS"
    echo "# Generated by scripts/time_build.sh" >> "$TIMINGS"
    echo "# Note: dune trace parsing incomplete, use ps monitoring for now" >> "$TIMINGS"
fi

echo "Timings saved to $TIMINGS"
echo "Trace saved to $TRACE"
