//! Generated by tests/generate_bn254_multilin.py — DO NOT EDIT BY HAND.
//!
//! Cross-check: e(k*G1, G2) == e(G1, G2)^k for k in {2,3,5,7,11}.
//! Both sides are computed inside the safe-Rust BN254 tower; the kP
//! coordinates are precomputed via Python's curve-law arithmetic.

use bn254::*;

// G1 generator (1, 2) in Montgomery form
const G1_X: Fp = Fp([15230403791020821917, 754611498739239741, 7381016538464732716, 1011752739694698287]);
const G1_Y: Fp = Fp([12014063508332092218, 1509222997478479483, 14762033076929465432, 2023505479389396574]);

// 2*G1 in Montgomery form
const K2_G1_X: Fp = Fp([16214190896527698488, 13550016860984857705, 14015815241649799916, 1378791528466284877]);
const K2_G1_Y: Fp = Fp([4332616871279656263, 10917124144477883021, 13281191951274694749, 316464129134141481]);

// 3*G1 in Montgomery form
const K3_G1_X: Fp = Fp([11349945508338274720, 10516340564297075582, 1073522015087498704, 1220681065426257209]);
const K3_G1_Y: Fp = Fp([13696893332200248298, 16748403329945737754, 5894261446386786634, 92646983456880915]);

// 5*G1 in Montgomery form
const K5_G1_X: Fp = Fp([5962560908110737257, 956008546028513767, 10141120004113640803, 3120535472679077436]);
const K5_G1_Y: Fp = Fp([17932343232170917889, 10208671136062734056, 18427887398183947538, 1591919978119415005]);

// 7*G1 in Montgomery form
const K7_G1_X: Fp = Fp([9812858345134030822, 14997041646296326421, 14175488229092925571, 1160245738820284093]);
const K7_G1_Y: Fp = Fp([4966352123909313295, 768671283811433612, 9511113118144511692, 2058676998349405580]);

// 11*G1 in Montgomery form
const K11_G1_X: Fp = Fp([15961161835219694078, 11679944753620289079, 11857460623656853934, 1297273668752035366]);
const K11_G1_Y: Fp = Fp([8022951945693482846, 11641680655316942957, 13718306900415351524, 1435631974854268331]);

// G2 generator (the same one used by examples/pairing_test.rs)
fn g2() -> (Fp2, Fp2) {
    let q_x = Fp2 {
        c0: Fp([0x8e83b5d102bc2026, 0xdceb1935497b0172, 0xfbb8264797811adf, 0x19573841af96503b]),
        c1: Fp([0xafb4737da84c6140, 0x6043dd5a5802d8c4, 0x09e950fc52a02f86, 0x14fef0833aea7b6b]),
    };
    let q_y = Fp2 {
        c0: Fp([0x619dfa9d886be9f6, 0xfe7fd297f59e9b78, 0xff9e1a62231b7dfe, 0x28fd7eebae9e4206]),
        c1: Fp([0x64095b56c71856ee, 0xdc57f922327d3cbb, 0x55f935be33351076, 0x0da4a0e693fd6482]),
    };
    (q_x, q_y)
}

/// Compute base^k in Fp12 by left-to-right square-and-multiply.
/// k must be a small positive integer.
fn fp12_pow_small(out: &mut Fp12, base: &Fp12, k: u64) {
    assert!(k >= 1);
    let mut acc = *base;
    let bits = 64 - k.leading_zeros();
    for i in (0..bits - 1).rev() {
        let prev = acc;
        bn254::fp12_square(&mut acc, &prev);
        if (k >> i) & 1 == 1 {
            let prev = acc;
            bn254::fp12_mul(&mut acc, &prev, base);
        }
    }
    *out = acc;
}

fn fp12_eq(a: &Fp12, b: &Fp12) -> bool {
    a.c0.c0.c0 == b.c0.c0.c0 && a.c0.c0.c1 == b.c0.c0.c1 &&
    a.c0.c1.c0 == b.c0.c1.c0 && a.c0.c1.c1 == b.c0.c1.c1 &&
    a.c0.c2.c0 == b.c0.c2.c0 && a.c0.c2.c1 == b.c0.c2.c1 &&
    a.c1.c0.c0 == b.c1.c0.c0 && a.c1.c0.c1 == b.c1.c0.c1 &&
    a.c1.c1.c0 == b.c1.c1.c0 && a.c1.c1.c1 == b.c1.c1.c1 &&
    a.c1.c2.c0 == b.c1.c2.c0 && a.c1.c2.c1 == b.c1.c2.c1
}

fn check(k: u64, kp_x: &Fp, kp_y: &Fp, q_x: &Fp2, q_y: &Fp2) -> bool {
    let mut e_pq = Fp12::zero();
    pairing_optimal(&mut e_pq, &G1_X, &G1_Y, q_x, q_y);
    let mut e_kpq = Fp12::zero();
    pairing_optimal(&mut e_kpq, kp_x, kp_y, q_x, q_y);
    let mut e_pq_k = Fp12::zero();
    fp12_pow_small(&mut e_pq_k, &e_pq, k);
    fp12_eq(&e_kpq, &e_pq_k)
}

fn main() {
    let (q_x, q_y) = g2();
    let mut all_ok = true;
    let ok2 = check(2, &K2_G1_X, &K2_G1_Y, &q_x, &q_y);
    println!("k=2: {}", if ok2 { "OK" } else { "FAIL" });
    all_ok &= ok2;
    let ok3 = check(3, &K3_G1_X, &K3_G1_Y, &q_x, &q_y);
    println!("k=3: {}", if ok3 { "OK" } else { "FAIL" });
    all_ok &= ok3;
    let ok5 = check(5, &K5_G1_X, &K5_G1_Y, &q_x, &q_y);
    println!("k=5: {}", if ok5 { "OK" } else { "FAIL" });
    all_ok &= ok5;
    let ok7 = check(7, &K7_G1_X, &K7_G1_Y, &q_x, &q_y);
    println!("k=7: {}", if ok7 { "OK" } else { "FAIL" });
    all_ok &= ok7;
    let ok11 = check(11, &K11_G1_X, &K11_G1_Y, &q_x, &q_y);
    println!("k=11: {}", if ok11 { "OK" } else { "FAIL" });
    all_ok &= ok11;
    if !all_ok {
        eprintln!("BN254 cross-check FAILED");
        std::process::exit(1);
    }
    println!("BN254 multilinearity cross-check PASS");
}
